### PR TITLE
Get video info even if no likes/dislikes exist

### PR DESCRIPTION
**Pull request by noembryo**
If no likes/dislikes exist we get 0 not `KeyError`..

### CODE REVIEW

**Review by bubblefoil — APPROVED** [review]

**Review by mts7 — APPROVED** [review]

**Comment by romainjouin** [comment]
I propose to change the lines 53 and 54 of file * backend_youtube_dl.py * to : 

self._likes = self._ydl_info.get('like_count',0)
self._dislikes = self._ydl_info.get('dislike_count',0)

**Comment by noembryo** [comment]
This is exactly what this PR is doing... :wink:

**Comment by hanngocduong97** [comment]
Good day, I have the same problem so can you merge this branch thank you!

**Comment by hanngocduong97** [comment]
Good day, I have the same problem so can you merge this branch thank you!

**Review by bubblefoil — APPROVED** [review]

**Comment by hvgupta** [comment]
I am getting 'like_count' error, how can I fix it?

**Review by Sujit27 — APPROVED** [review]

**Comment by Coddo-Python** [comment]
Has the PR been merged yet?

**Comment by bubblefoil** [comment]
> 
> 
> Has the PR been merged yet?

image

Apparently, we don't have the power and those who do don't care 🤷 
I don't even know how to find a person with write access.

**Review by blluv — APPROVED** [review]

**Review by ritiek — APPROVED** [review]

**Comment by ritiek** [comment]
Looks good to me, thanks! By the way, I encourage all of you guys to check out [pytube](https://github.com/pytube/pytube) and see if it fits your needs, since it's more actively maintained.

Really sorry I couldn't get this to merge earlier since I'm not actively working on pafy any more (and it seems like other maintainers have gone busy too). :(

**Comment by Coddo-Python** [comment]
But ritiek, pafy is like WAYYYYY faster than pytube as ytdl, I have done tests, pafy was faster 100% of the time

**Comment by Rutvik552k** [comment]
I have made changes as per the suggestion of @romainjouin in backend_youtube_dl.py file. although i am facing keyerror "Like count". Could anyone help me to resolve this?

Ans. I just comment out those both line and my code works.

**Pull request merged**
