### PR TITLE
Use gdata.youtube.com for get_playlist; support more than 200 songs

### LINKED ISSUE #71: Support Playlists Longer Than 200 Songs
This was reported as an issue in mpsyt (np1/mps-youtube#192) but it is a problem with pafy.

Youtube will return a maximum of 200 songs.  The solution to this is to send an additional request requesting another max 200 songs.

I can't seem to find any documentation on http://www.youtube.com/list_ajax, but I am guessing that it is version 1 of Youtube's API.  It seems like it would be better to use http://gdata.youtube.com/feeds/api/playlists/%s?v=2.  I have tried to change this, but it seems it will require modifications to several parts of the code, including the Pafy class.

The advantage of using this api is that it provides a good way to get additional songs.  Something like this will get the url for the next list of videos:

    url = next((i for i in t.finditer(t1 + 'link')
                     if i.get('rel') == 'next'), None).get('href')

I will see if I can find a way to get this to work with the list_ajax api.

### PR DESCRIPTION
**Pull request by ids1024**
This fixes #71.

This also removes some parameters unused by either pafy or mpsyt that
seemed difficult to implement with the new API.

There may be issues that need fixing.  If nothing else, the definition of vid_data looks quite ugly.

Edit: The parameters I deleted should be added if possible.

### CODE REVIEW

**Comment by ids1024** [comment]
Here is what I have not implemented:
* added
* is_cc
* privacy
* start
* keywords
* cc_license
* category_id
* time_updated
* end

I have also removed the playlist description, likes, and dislikes.

Some of these may be easy to add back, while others seem to be missing from YouTube's response.

**Comment by ids1024** [comment]
@np1 Have you looked at the changes here?  It does not provide all the data the currently implementation does, so it is probably not ready to merge.  As far as I can tell, playlist likes and dislikes are not available with the new api.  I can't find that on youtube.com either, so the feature was probably removed.  Some of the others may also not be available with the new api,.

**Comment by np1** [comment]
Nope I haven't had a chance to look at it yet. Thanks for the PR. I will try to get to it soon.

**Comment by np1** [comment]
I am reluctant to include any changes that use gdata v2 because it will be turned off in the coming months.

"Note: The YouTube Data API (v2) has been deprecated as of February 26, 2014. In keeping with our deprecation policy, most API functionality that was subject to that policy will continue to be available until April 20, 2015. Support for some API features may be discontinued earlier if the corresponding features are also removed from YouTube prior to that date. See the Deprecation FAQ for answers to frequently asked questions about the deprecation."


Using v3 of the api requires obtaining a key for most request types - and obtaining a key requires agreeing to not access YouTube in the way that pafy does.

Some things specifically prohibited;

    - access any portion of any YouTube audiovisual content by any means other than use of a YouTube player or other video player expressly authorized by YouTube;
    - store copies of YouTube audiovisual content;




https://developers.google.com/youtube/2.0/developers_guide_protocol_deprecated
https://developers.google.com/youtube/youtube-api-list
https://developers.google.com/youtube/terms

I'm not sure how best to proceed at the moment..

**Comment by ids1024** [comment]
Version 3 of the api should be more similar to version 2 than what is currently used, so this is a step towards using that version.  The TOS could be problematic, but I don't know what can be done.

**Comment by ids1024** [comment]
Superseded by #127.

**Pull request closed without merging**
